name: ✨ Feature Request
description: Suggest a new feature or enhancement for Telescope.browser
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What use case does it address?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: I've also considered...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the extension would this feature affect?
      options:
        - Tab Search
        - Harpoon System
        - Visual Mode
        - Keyboard Navigation
        - UI/UX
        - Performance
        - Settings/Configuration
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Really need this

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples to help explain your feature
      placeholder: You can drag and drop images here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional information...