name: CI Pipeline

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Cypress binary
      run: npx cypress install
      
    - name: Run TypeScript type checking
      run: npm run check
      
    - name: Run linting
      run: npm run lint
      
    - name: Run build
      run: npm run build
      
    - name: Verify extension build
      run: |
        echo "Extension files:"
        ls -la dist/
        ls -la dist/content-scripts/
        echo "Manifest contents:"
        cat dist/manifest.json
      
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Setup Chrome for Testing
      id: setup-chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable  # This installs Chrome for Testing
        
    - name: Install xvfb for headed mode
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - name: Run E2E tests with Chrome for Testing in headed mode
      run: |
        echo "Chrome for Testing path: ${{ steps.setup-chrome.outputs.chrome-path }}"
        echo "Chrome for Testing version: ${{ steps.setup-chrome.outputs.chrome-version }}"
        echo "Using Chrome for Testing in headed mode (extensions require headed mode)"
        xvfb-run -a npx cypress run --browser "${{ steps.setup-chrome.outputs.chrome-path }}" --headed --config chromeWebSecurity=false
      
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: chrome-telescope-build-${{ github.sha }}
        path: dist/
        retention-days: 7
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.sha }}
        path: |
          cypress/screenshots/
          cypress/videos/
        retention-days: 7
        if-no-files-found: ignore